# Generated by Django 3.0.4 on 2020-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='abcdef', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
