# Generated by Django 3.0.4 on 2020-04-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0004_answer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='slug',
            new_name='ans_slug',
        ),
    ]
