# Generated by Django 3.0.4 on 2020-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0005_auto_20200407_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='null', upload_to='media/'),
        ),
    ]
