# Generated by Django 3.0.4 on 2020-04-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0008_auto_20200414_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriveVilla.Advertisement')),
            ],
        ),
    ]
