# Generated by Django 3.0.4 on 2020-04-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0009_auto_20200414_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdImages',
            new_name='AdImage',
        ),
    ]
