# Generated by Django 3.0.4 on 2020-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0011_auto_20200424_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
