# Generated by Django 3.0.4 on 2020-05-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0017_auto_20200505_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
