# Generated by Django 3.0.4 on 2020-05-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0020_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='key',
        ),
    ]
