# Generated by Django 3.0.4 on 2020-05-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0021_remove_active_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
    ]
