# Generated by Django 3.0.4 on 2020-05-22 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DriveVilla', '0023_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active',
            new_name='ActiveUser',
        ),
    ]
