# Generated by Django 3.0.4 on 2020-08-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0024_auto_20200522_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBotMessage',
        ),
    ]
