# Generated by Django 3.0.4 on 2020-09-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveVilla', '0026_chatbotmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBotMessage',
        ),
    ]
